/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export function add(a: number, b: number): number
export function getData(url: string): Promise<string>
